name: debug android
on:
  #push:
  #  branches:
  #    - '**'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

# does not work as expected with gradle-version: current
env:
  GRADLE_VERSION: 8.14.1

jobs:
  build_apk_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Download Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > composeApp/coshanu-android-release.jks

      # todo remove
      - name: Debug Keystore
        run: |
          ls -l composeApp/coshanu-android-release.jks
          keytool -list -v -keystore composeApp/coshanu-android-release.jks -storepass ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        env:
          storePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          arguments: >-
            :composeApp:packageReleaseApk
            -PstorePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
            -PkeyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
            -Pandroid.injected.signing.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
            -Pandroid.injected.signing.key.alias=${{ secrets.ANDROID_KEY_ALIAS }}
            -Pandroid.injected.signing.key.password=${{ secrets.ANDROID_KEY_PASSWORD }}
          #arguments: :composeApp:packageReleaseApk
          #arguments: >-
          #  assembleRelease
#            :composeApp:packageReleaseApk
#            -Pandroid.injected.signing.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
#            -Pandroid.injected.signing.key.alias=${{ secrets.ANDROID_KEY_ALIAS }}
#            -Pandroid.injected.signing.key.password=${{ secrets.ANDROID_KEY_PASSWORD }}
