name: debug proguard
on:
  push:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  build_linux_deb_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      # todo remove
      - name: Check for proguard file
        run: |
          ls -l ./composeApp
          cat composeApp/proguard-rules.pro || echo "composeApp/proguard-rules.pro not found"

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: :composeApp:packageReleaseDeb

  build_linux_deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      # todo remove
      - name: Check for proguard file
        run: |
          ls -l ./composeApp
          cat composeApp/proguard-rules.pro || echo "composeApp/proguard-rules.pro not found"

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: :composeApp:packageDeb
